cookie:
  expiry_days: 30
  key: medghor_secret_key_2025
  name: medghor_cookie
credentials:
  usernames:
    admin2025:
      email: admin@medghor.com
      failed_login_attempts: 0
      first_name: Admin
      last_name: Medghor
      logged_in: false
      password: $2b$12$7.suWCqiuEthLaNhDgZud.vWrmcbkqdeRavjPTk4RIMy48E26RIxS
      roles:
      - admin
pre-authorized:
  emails: []
